### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by MephistoSatanDevil**

### CODE REVIEW

**Comment by 11jo** [comment]
I got errors while trying to install your fork, have you tried to install yourself ?

Your files should be in GB2312 except for install.tra, I think...

**Comment by MephistoSatanDevil** [comment]
> I got errors while trying to install your fork, have you tried to install yourself ?
> 
> Your files should be in GB2312 except for install.tra, I think...

Sorry, it was my oversight, it has been corrected.

**Comment by 11jo** [comment]
Yes I was thinking about it since the mod is bgee only, but I am mostly sure that it could easly work with BGT, like Saradas for Bg2.

To see when I got some time to check everything and make changes accordingly.

Thanks for the translation, it is the definitive version or some proofreading are planned ?

**Comment by MephistoSatanDevil** [comment]
> Yes I was thinking about it since the mod is bgee only, but I am mostly sure that it could easly work with BGT, like Saradas for Bg2.
> 
> To see when I got some time to check everything and make changes accordingly.
> 
> Thanks for the translation, it is the definitive version or some proofreading are planned ?

After mod install, two English entries were added, which are the @21 and @22 entries from setup.tra. However, these two entries have already been translated correctly in Install.tra.

The translation is currently considered complete. 

However, the Chinese version of the Baldur's Gate game is currently undergoing comprehensive proofreading and is updated quite frequently. To ensure the consistency and accuracy of the translations, various mods may also be updated accordingly. You can merge this pull request (PR) first, and if there are any updates in the future, we will submit them again.

**Comment by 11jo** [comment]
After testing again, the mod install but all text related to setup.tra is in english.

At the end there is nothing to put in install.tra since the only prompt is not traified.

And install.tra should be used only for prompt, not for translation.

Please try to reinstall and verify if items and spells have chinese translation on your side.

**Comment by MephistoSatanDevil** [comment]
> After testing again, the mod install but all text related to setup.tra is in english.
> 
> At the end there is nothing to put in install.tra since the only prompt is not traified.
> 
> And install.tra should be used only for prompt, not for translation.
> 
> Please try to reinstall and verify if items and spells have chinese translation on your side.

Because the setup.tra file does not contain any prompt content, my previous modification to the install encoding was useless.
Now I have reverted it, and after testing, everything is working perfectly normal.

**Pull request merged**
